language: ruby
rvm:
- 2.1

exclude: [vendor]

script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx
# --check-html does not work for us:
# https://groups.google.com/forum/#!topic/nokogiri-talk/Sz6JCmXHUXU
# https://github.com/sparklemotion/nokogiri/issues/1243

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
