language: ruby
rvm:
- 2.1

exclude: [vendor]

script:
  - bundle exec jekyll build
#  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html
  - bundle exec htmlproof ./_site --only-4xx --check-html

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
