# Site settings
title: "The Honeynet Project: Polish Chapter"
email: hnp@cert.pl
description: # this means to ignore newlines until "baseurl:"
  HNP/P/PL
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pl.honeynet.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
